Fix the CI builds
royshil/obs-backgroundremoval pull request #152
Opened 2023-03-01 11:42 UTC by umireon

I worked on the new CI system and got it to create the binaries for each platform.
Is there any possibility of merging my work?

2023-03-05 02:54 UTC, royshil commented
Thank so much @umireon  for the work!

i've merged my own CI work - can you please merge/rebase your work?

2023-03-05 03:01 UTC, umireon commented
This PR will fix Windows and Linux builds.
Also it uses ExternalProject to build this plugin's own static libonnxruntime and static libopencv that is built with the minimal configuration provided in make sh.
macOS and linux builds don't need additional DLLs and Windows build needs DirectML.dll but it will be included into the bundle automatically.

2023-03-05 03:01 UTC, umireon commented
@royshil Merged!

2023-03-05 03:11 UTC, royshil commented on cmake/BuildMyOnnxruntime.cmake
> +include(ExternalProject)
can you please run `cmake-format` to get these to appease the linter?

i can do it too if you don't have `cmake-format` going on your env, let me know

2023-03-05 03:14 UTC, umireon commented on cmake/BuildMyOnnxruntime.cmake
> +include(ExternalProject)
Fixed!

2023-03-05 03:18 UTC, royshil commented on buildspec.json
> +            "version": "28.0.1",
🤔  OBS 29.0.x is already out... i think we should support it no?

2023-03-05 03:24 UTC, umireon commented on buildspec.json
> +            "version": "28.0.1",
I think it is great if the minimal supported version is the lowest (28 for Qt6) because we don't use 29 features. However, I'm OK for building with 29😊

2023-03-05 03:29 UTC, royshil commented on buildspec.json
> +            "version": "28.0.1",
if we build for 28 - will it work for people on 29?

2023-03-05 03:31 UTC, umireon commented on buildspec.json
> +            "version": "28.0.1",
The answer is yes - This works great on my latest OBS 29 installation of Apple Silicon🍎

2023-03-05 03:38 UTC, umireon commented
@royshil If you put a label named `Seeking Testers` on this PR, the result binaries will be available on the GitHub Actions Summary screen.

2023-03-05 03:40 UTC, umireon commented
CI takes 1 hour for the first time. Once this PR merged into master, the compilation cache will be enabled for all the platforms and CI will end in 10 minutes.

2023-03-05 03:41 UTC, royshil commented on cmake/BuildMyOpenCV.cmake
> +    <INSTALL_DIR>/${OpenCV_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}opencv_imgcodecs${OpenCV_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
i think we only need `core` and `imgproc`

2023-03-05 03:42 UTC, royshil commented on buildspec.json
> +            "version": "28.0.1",
ok cool keep it at 28 then.

2023-03-05 03:44 UTC, umireon commented on cmake/BuildMyOpenCV.cmake
> +    <INSTALL_DIR>/${OpenCV_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}opencv_imgcodecs${OpenCV_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
My fault 🙇

2023-03-05 03:44 UTC, royshil commented
> CI takes 1 hour for the first time. Once this PR is merged into main, the compilation cache will be enabled for all the platforms and CI will end in 10 minutes.

yes i suspected as much, seeing the ccache work in the cmake files

my preference would be to have a precompiled binary we just download from S3.. but let's see how ccache does first

2023-03-05 03:44 UTC, umireon commented on cmake/BuildMyOpenCV.cmake
> +    <INSTALL_DIR>/${OpenCV_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}opencv_imgcodecs${OpenCV_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
Fixed!

2023-03-05 03:49 UTC, royshil commented
@umireon  i'm going to cancel the new build action and keep the old one going (to hopefully keep the ccache), before i let the latest commit one start running

2023-03-05 04:42 UTC, royshil requested changes

2023-03-05 04:42 UTC, royshil commented on cmake/BuildMyOnnxruntime.cmake
> +            ${INSTALL_DIR}/include/onnxruntime/core/session
to tackle this problem
```/Users/runner/work/obs-backgroundremoval/obs-backgroundremoval/plugin/src/background-filter.cpp:5:10: fatal error: 'core/session/onnxruntime_cxx_api.h' file not found
#include <core/session/onnxruntime_cxx_api.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
it also needs just
`${INSTALL_DIR}/include/onnxruntime`

2023-03-05 09:37 UTC, umireon commented on cmake/BuildMyOnnxruntime.cmake
> +            ${INSTALL_DIR}/include/onnxruntime/core/session
Added!

2023-03-06 03:40 UTC, umireon commented
@royshil Some build errors remained so I've fixed bugs!

2023-03-06 03:48 UTC, umireon commented
Ccache won't work until the cache is created on the main branch.

2023-03-06 14:10 UTC, umireon commented on cmake/BuildMyOpenCV.cmake
> +target_include_directories(OpenCV INTERFACE ${OpenCV_INCLUDE_PATH})
set_target_properties(OpenCV
                      PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${OpenCV_INCLUDE_PATH})

2023-03-06 14:34 UTC, umireon commented
@royshil Linux build failure will be fixed with [aad1d61](https://github.com/royshil/obs-backgroundremoval/pull/152/commits/aad1d614aaeb98b101b30527c25b45a15f18f1d9)

2023-03-06 15:43 UTC, umireon commented
@royshil Argument number error in CMakeFiles.txt was fixed!

2023-03-06 18:18 UTC, umireon commented
I've misunderstood about INTERFACE_INCLUDE_DIRECTORIES. Now fixed @royshil

2023-03-06 20:48 UTC, royshil commented
@umireon you're almost there! got a couple minor snags

you can feel free to disable warning-to-error flag, and the compile error will go away (because it's a warning)

2023-03-07 10:11 UTC, umireon commented
@royshil /WX and -Werror is disabled!

2023-03-07 10:13 UTC, umireon commented
CCache is already effective on Mac

2023-03-07 12:18 UTC, royshil approved these changes
Nice work! Let's bring it in

2023-03-07 12:23 UTC, merged