Flatpak
royshil/obs-backgroundremoval pull request #198
Opened 2023-03-21 10:35 UTC by umireon

2023-03-21 14:03 UTC, bergmannf commented
Only problem I faced when I wanted to build this locally is that the archive downloaded is pointing to HEAD and the SHA256 commit was incorrect - changing the block the following makes it work for me:

```yaml
      - type: archive
        url: https://github.com/royshil/obs-backgroundremoval/archive/refs/heads/umireon.flatpak-build.tar.gz
        sha256: b8be520c9f12afb4689b04b237c3f3d17c4c9b1dcac61bbb89533b3ede35b8c4
```

2023-03-21 14:41 UTC, royshil requested changes
license is an issue for me.

2023-03-21 14:41 UTC, royshil commented on ci/flatpak/com.obsproject.Studio.Plugin.Backgroundremoval.yaml
> +        sha256: ff5c8078507a42c5188f9d51440530e8466859a7f34d5f9b09708d9423240840
this needs to be automatically filled up externally no?

2023-03-21 14:41 UTC, royshil commented on ci/flatpak/com.obsproject.Studio.Plugin.Backgroundremoval.metainfo.xml
> +  <project_license>GPL-2.0</project_license>
i feel very uncomfortable changing the license to GPL 2.
MIT is a far more permissive license.

2023-03-21 14:49 UTC, royshil commented
> I confirmed that these files can generate the right flatpak distribution. @royshil Can you submit these files to FlatHub and make them available on FlatHub? https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app

i will submit naturally as soon as we land this and release 0.5.15
and fix the SHA

2023-03-21 15:25 UTC, umireon commented on ci/flatpak/com.obsproject.Studio.Plugin.Backgroundremoval.metainfo.xml
> +  <project_license>GPL-2.0</project_license>
I know that but we are forced to use GPL-2.0. Of course, I'm against GPL.
I revert this change when https://github.com/royshil/obs-backgroundremoval/pull/199 is rejected.

2023-03-21 15:26 UTC, umireon commented on ci/flatpak/com.obsproject.Studio.Plugin.Backgroundremoval.yaml
> +        sha256: ff5c8078507a42c5188f9d51440530e8466859a7f34d5f9b09708d9423240840
This should be version

2023-03-21 15:30 UTC, royshil commented on ci/flatpak/com.obsproject.Studio.Plugin.Backgroundremoval.metainfo.xml
> +  <project_license>GPL-2.0</project_license>
we can go to GPLv2
it's unfortunate. very restrictive...
but all of OBS is GPLv2 and even the obs-plugintemplate which this plugin came from! 🤣

2023-03-21 15:45 UTC, umireon commented
I'm not going to merge this PR into this repo.
It would rather be good to send the content of this PR with v0.5.15 SHAs to FlatHub.

2023-03-21 15:45 UTC, umireon commented on ci/flatpak/com.obsproject.Studio.Plugin.Backgroundremoval.metainfo.xml
> +  <project_license>GPL-2.0</project_license>
Yeah that true

2023-03-21 17:23 UTC, royshil commented
> I'm not going to merge this PR into this repo. It would rather be good to send the content of this PR with v0.5.15 SHAs to FlatHub.

let me know when to submit the package to flathub

2023-03-21 18:17 UTC, umireon commented
@royshil 
> let me know when to submit the package to flathub

It would be great to submit it right after v0.5.15 is out.
V0.5.15 must include https://github.com/royshil/obs-backgroundremoval/pull/203 for a successful Flatpak build.
I will change the contents of Flatpak metadata on this PR for v0.5.15 so that you can use the files on this PR for submitting to FlatHub.

2023-03-26 18:01 UTC, royshil approved these changes
lets land this

2023-03-26 18:01 UTC, royshil commented
theres a PR to bring it up in flathub https://github.com/flathub/flathub/pull/4016

2023-03-27 03:54 UTC, umireon commented
Thank you! It seemed to work on FlatHub!

2023-04-20 02:56 UTC, umireon commented
@royshil Can you update the PR for FlatHub?

2023-05-09 07:49 UTC, umireon commented
This plugin on the FlatHub have been released 🎉

2023-05-09 07:49 UTC, closed without merging

2023-05-09 07:52 UTC, umireon commented
You can install this plugin via this command:

```
flatpak install com.obsproject.Studio.Plugin.BackgroundRemoval
```