Remove MODNET model
royshil/obs-backgroundremoval pull request #209
Opened 2023-03-24 03:11 UTC by royshil

The MODNET model is heavy in size (20Mb) and it's accuracy is low compared to the others.

we have pretty good models already, so we can cut back

2023-03-24 06:55 UTC, umireon requested changes

2023-03-24 06:55 UTC, umireon commented on cmake/BuildMyOnnxruntime.cmake
I suppose your changes in BuildMyOnnxruntime.cmake would break the Linux build.

2023-03-24 07:01 UTC, umireon commented on cmake/BuildMyOnnxruntime.cmake
libonnxruntime_session.a must come first in CMake.

2023-03-24 07:55 UTC, umireon commented on cmake/BuildMyOnnxruntime.cmake
I've confirmed that these changes in BuildMyOnnxRuntime.cmake broke the Linux build.

<img width="1136" alt="スクリーンショット 2023-03-24 16 53 45" src="https://user-images.githubusercontent.com/1067855/227458721-405e7806-eb59-498a-b502-f86142fcc93f.png">

2023-03-24 18:27 UTC, royshil commented
@umireon i was mistaken. i accidentally checked in the Cmake changes - where i shouldnt
but i've reverted hthem now
can you check it out please?

2023-03-25 03:57 UTC, umireon approved these changes
LGTM!

2023-03-25 16:40 UTC, merged