Fix #212
royshil/obs-backgroundremoval pull request #213
Opened 2023-03-26 06:13 UTC by umireon

https://github.com/royshil/obs-backgroundremoval/issues/212

2023-03-26 17:45 UTC, royshil requested changes
i'm not sure this is the solution we need..

2023-03-26 17:45 UTC, royshil commented on src/background-filter.cpp
> +  frame->data[0] = static_cast<uint8_t *>(brealloc(data0, imageBGRA.cols * imageBGRA.rows * 16));
why do we have to alloc `* 16` here? shouldn't it be just `*4` for RGBA?

also, `imageRGBA` is packed `RGBARGBARGBA`
while it seems `frame->data` is planar packed e.g. `RRRRRR..... GGGGGG...... BBBBBBB..... AAAAAAA`
so we can't memcpy?

also, where do we free this memory?

2023-03-27 03:50 UTC, umireon commented on src/background-filter.cpp
> +  frame->data[0] = static_cast<uint8_t *>(brealloc(data0, imageBGRA.cols * imageBGRA.rows * 16));
> why do we have to alloc * 16 here? shouldn't it be just *4 for RGBA?

I checked the OBS source code and I found that the maximum size of a data plane is BGRA's and its size is `width * height * 4`.
The current maximum number of planes is 4 so we have to keep `frame->data[3]` allocated.
Thus I want to allocate width * height * 4 to 4 data planes as a proof of concept.

https://github.com/obsproject/obs-studio/blob/90f46a9d4dda4842325e513f5b3bcdc395a37803/libobs/media-io/video-frame.c#L23

Indeed, we can allocate memory more efficiently but it would need to create a different logic on the input frame->format.
I just want to keep the implementation simple for the first time.

> also, imageRGBA is packed RGBARGBARGBA

No, BGRABGRABGRA...

> while it seems frame->data is planar packed e.g. RRRRRR..... GGGGGG...... BBBBBBB..... AAAAAAA
> so we can't memcpy?

I instructed OBS to read data[0] as BGRABGRABGRA....

```
frame->format = VIDEO_FORMAT_BGRA;
```

ImageBGRA is packed as BGRA and thus imageBGRA.data and data[0] have the same structure as BGRA so they can memcpyed.

> also, where do we free this memory?

OBS will free frame->data[0] when OBS exits.
OBS assumes that frame->data[1+] must be freed by freeing frame->data[0].
Note that I have decided to call brealloc and no new pointers are allocated.

2023-03-27 04:35 UTC, royshil requested changes

2023-03-27 04:35 UTC, royshil commented on src/background-filter.cpp
> +  frame->data[0] = static_cast<uint8_t *>(brealloc(data0, imageBGRA.cols * imageBGRA.rows * 16));
if we're using only `frame->data[0]` why are we setting the `[1],[2],..` ?
those pointers would be "grabage", they are pointing to a place in the data that doesn't mean much
since all the data is already packed in `data[0]`

also `VIDEO_FORMAT_BGRA` - does it imply `BGRABGRABGRA` packing? or is it planar like `BBB GGG RRR AAA`?

2023-03-27 04:35 UTC, royshil commented on src/background-filter.cpp
> +  frame->data[3] = frame->data[1] + (data3 - data1);
if we're not using `data[1], data[2]` etc. - why not simply `frame->data[1] = data1` and so on?

2023-03-27 05:26 UTC, umireon commented
Since we make output with BGRA, the size of data[0] has to be `width * height * 4` and linesize[0] has to be `width * 4`.

OBS reuses `frame` between frames.

I will illustrate the case of NV12.
The size of data[0] must be more than `width` and linesize[0] must be more than `width` with NV12.
The redundant area is simply ignored so it is okay to have more size and more linesize than required.
We want to extend the size of data[0] and the address of data[0] may change after data[0] is reallocated.
When OBS starts the frame, OBS reuses data[0] and data[1] on the `frame` that we returned.
Therefore, the pointer of data[1] must be valid when we return the `frame` on our plugin.
To keep data[1] valid, we have to set a pointer based on the new data[0] to data[1].

I admit this is hacky but at least it works.
I think it would be great if we can output with gs_ functions as the Chroma Key filter does.

2023-03-27 05:27 UTC, umireon commented
> also VIDEO_FORMAT_BGRA - does it imply BGRABGRABGRA packing? or is it planar like BBB GGG RRR AAA?

VIDEO_FORMAT_BGRA implies BGRABGRABGRA packing!

2023-03-28 03:56 UTC, merged