Use Kawase Blur
royshil/obs-backgroundremoval pull request #276
Opened 2023-04-24 18:26 UTC by umireon

Fixes #271

https://www.intel.com/content/www/us/en/developer/articles/technical/an-investigation-of-fast-real-time-gpu-based-image-blur-algorithms.html#:~:text=%C2%A0%22Kawase%20blur%22%20filter

2023-04-24 19:36 UTC, royshil requested changes
this looks good - but lets clean it up first

2023-04-24 19:36 UTC, royshil commented on src/background-filter.cpp
> +  for (int i = 0; i < (int)tf->blurBackground; i++) {
we can move many things out of the loop...

2023-04-24 19:36 UTC, royshil commented on src/background-filter.cpp
> +  gs_texture_t *blurredTexture = gs_texture_create(width, height, GS_BGRA, 1, nullptr, 0);
we should only perform any of this if `tf->backgroundBlur > 0`

2023-04-25 03:55 UTC, umireon commented on src/background-filter.cpp
> +  for (int i = 0; i < (int)tf->blurBackground; i++) {
Fixed

2023-04-25 03:55 UTC, umireon commented on src/background-filter.cpp
> +  gs_texture_t *blurredTexture = gs_texture_create(width, height, GS_BGRA, 1, nullptr, 0);
Fixed!

2023-04-25 13:46 UTC, royshil approved these changes
nice! well done! go

2023-04-25 13:58 UTC, royshil commented
@umireon  wait! we got a problem
works great in the filters screen
![image](https://user-images.githubusercontent.com/441170/234299920-ac3a3221-470d-4d3e-a678-0717785f99be.png)
but in the main view....
![image](https://user-images.githubusercontent.com/441170/234300045-2bb7d808-b4fb-4aea-a530-c244c981e85f.png)
we have a problem

2023-04-25 14:32 UTC, umireon commented
On my side, everything works fine.

<img width="1191" alt="スクリーンショット 2023-04-25 23 31 21" src="https://user-images.githubusercontent.com/1067855/234309956-1f91a8f3-2c73-4029-b5aa-8b7d04b218b9.png">
<img width="1103" alt="スクリーンショット 2023-04-25 23 31 18" src="https://user-images.githubusercontent.com/1067855/234309972-7794d2a9-c9f3-4706-8eb4-b83211efb242.png">

2023-04-25 19:33 UTC, royshil commented
@umireon i'm still having a problem, and getting a strange error on the log
```
14:26:30.848: device_texture_create (D3D11): Failed to create 2D texture (80070057)
14:26:30.848: [obs-backgroundremoval] Failed to create alpha texture
14:26:30.853: device_texture_create (D3D11): Failed to create 2D texture (80070057)
14:26:30.853: [obs-backgroundremoval] Failed to create alpha texture
```
this error doesn't come up on the main version of the plugin.

so i think it's related to this change you're proposing here

2023-04-26 04:17 UTC, umireon commented
@royshil Can you paste the full log here?

2023-04-26 04:42 UTC, umireon commented
I could reproduced the problem on my side

<img width="1552" alt="スクリーンショット 2023-04-26 13 40 57" src="https://user-images.githubusercontent.com/1067855/234471694-061d5b99-bd8e-43ed-b1f2-4aec3d11ad3d.png">

2023-04-26 05:12 UTC, umireon commented
Fixed

2023-04-26 15:32 UTC, royshil approved these changes
confirmed to fix the problem - fire at will! 🚀

2023-04-26 15:34 UTC, merged