Add libcurl to fetch GitHub metadata
royshil/obs-backgroundremoval pull request #365
Opened 2023-07-01 13:45 UTC by umireon

2023-07-01 16:12 UTC, umireon commented
I have confirmed that this works on Windows, Linux, and macOS

2023-07-02 18:36 UTC, royshil requested changes
excellent stuff!!
but let's talk through it a bit

2023-07-02 18:36 UTC, royshil commented on CMakeLists.txt
> +set(MbedTLS_DIR ${CMAKE_PREFIX_PATH})
let's get all of this to an extrnal file in `cmake/`
like `BuildibCurl.cmake` or something
and the `include()` it here

2023-07-02 18:36 UTC, royshil commented on CMakeLists.txt
> +add_subdirectory(vendor/curl EXCLUDE_FROM_ALL)
why submodule and not what we do with OpenCV? e.g. the CMake external build

2023-07-02 18:36 UTC, royshil commented on build-aux/run-cmake-format
> +      source_files=(${source_files:#(vendor)/*})
i don't think we should format other people's code...

2023-07-02 18:36 UTC, royshil commented on src/update-checker/github-utils.cpp
> +static const char USER_AGENT[] = "obs-backgroundremoval/1.0.3";
this must come from the existingplugin build...

2023-07-02 18:36 UTC, royshil commented on src/update-checker/github-utils.cpp
> +		obs_log(LOG_INFO, "%s\n", str.c_str());
i think `blog` should be availale

2023-07-02 18:45 UTC, umireon commented on CMakeLists.txt
> +add_subdirectory(vendor/curl EXCLUDE_FROM_ALL)
Originally I want ONNX Runtime and OpenCV to be submodules because it is easy to debug.
However, their library definitions are odd and it is hard to use add_subdirectory.
Therefore I have concluded that they should reside in FetchContent.

On the other hand. the library definition of libcurl is straight-forward and it can be added by target_link_libraries.
I want to stick to the simpler way this time..

2023-07-02 18:46 UTC, umireon commented on build-aux/run-cmake-format
> +      source_files=(${source_files:#(vendor)/*})
This line instructs cmake-format to exclude the vendor directory.
This is not adding the vendor directory but removing vendor directory.

2023-07-02 18:48 UTC, umireon commented on src/update-checker/github-utils.cpp
> +static const char USER_AGENT[] = "obs-backgroundremoval/1.0.3";
I couldn't find a way to concatenate the string stored in static variables in the compile time.
Do you know any good way?

2023-07-02 18:51 UTC, royshil commented on src/update-checker/github-utils.cpp
> +static const char USER_AGENT[] = "obs-backgroundremoval/1.0.3";
you can just use a `.cpp.in` "config" file and use CMake's `config` to fill in the version from the CMake variables and generate the real `.cpp` file
but you can do the concatenation later e.g. with `std::string(USER_AGENT_PREFIX) + std::string(PLUGIN_VERSION)` or similar when you go to fetch the URL

2023-07-02 18:51 UTC, umireon commented on src/update-checker/github-utils.cpp
> +		obs_log(LOG_INFO, "%s\n", str.c_str());
Fixed

2023-07-02 18:59 UTC, umireon commented on CMakeLists.txt
> +set(MbedTLS_DIR ${CMAKE_PREFIX_PATH})
Fixed

2023-07-02 19:04 UTC, umireon commented on src/update-checker/github-utils.cpp
> +static const char USER_AGENT[] = "obs-backgroundremoval/1.0.3";
Fixed

2023-07-03 12:44 UTC, royshil approved these changes
LGTM!

2023-07-03 12:50 UTC, merged